version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout

      - restore_cache: 
          keys: 
            - v1-dependencies-{{ checksum "pyproject.toml" }}
            - v1-dependencies-
      
      - run: 
          name: install poetry
          command: |
            curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
            ~/.poetry/bin/poetry install

      -run:
          name: download NCBI taxonomy database
          command: |
            mkdir data
            curl --output data/taxdump.tar.gz https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz
            curl --output data/taxdump.tar.gz.md5 https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz.md5
            cd data
            md5sum -c taxdump.tar.gz.md5

      - run:
          name: generate sqlite3 taxdb database
          command: |
            ~/.poetry/bin/poetry run python -c 'from ncbi_taxid.taxid_utils import TaxIDExpander; t = TaxIDExpander(taxdump_filename="data/taxdump.tar.gz", taxdb_filename="data/taxdb.sqlite3")'

      - save_cache:
          paths:
            - ./.cache
            - ./data
          keys:
            - v1-dependencies-{{ checksum "pyproject.toml" }}

      - run:
          name: run tests
          command:
            export NCBI_TAX_DB=data/taxdb.sqlite3
            export NCBI_TAXDUMP_FILE=data/taxdump.tar.gz
            ~/.poetry/bin/poetry run pytest
  