version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
        environment:
          NCBI_TAX_DB: data/taxdb.sqlite3
          NCBI_TAXDUMP_FILE: data/taxdump.tar.gz
          
    steps:
      - checkout

      - restore_cache: 
          keys: 
            - v1-dependencies-{{ checksum "pyproject.toml" }}
            - v1-dependencies-
      
      - run: 
          name: install poetry
          command: |
            if [[ ! -d ~/.poetry ]] ; then 
              curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
              ~/.poetry/bin/poetry install
            fi

      - run:
          name: download NCBI taxonomy database
          command: |
            if [[ ! -d data/ ]] ; then 
              mkdir data
              curl --output data/taxdump.tar.gz https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz
              curl --output data/taxdump.tar.gz.md5 https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz.md5
              cd data
              md5sum -c taxdump.tar.gz.md5
            fi

      - run:
          name: generate sqlite3 taxdb database
          command: |
            if [[ ! -f $NCBI_TAX_DB ]] ; then
              ~/.poetry/bin/poetry run python -c "from diamond_add_taxonomy.taxid_utils import TaxIDExpander; t = TaxIDExpander(taxdump_filename='$NCBI_TAXDUMP_FILE', taxdb_filename='$NCBI_TAX_DB')"
            fi

      - save_cache:
          key: v1-dependencies-{{ checksum "pyproject.toml" }}
          paths:
            - ./.cache
            - ./data

      - run:
          name: run tests
          command:
            ~/.poetry/bin/poetry run pytest
  